name: fica
channels:
  - defaults
  - invenia
  - picos
  - gurobi
  - conda-forge

dependencies:
  - python=3.9.19
  - pip
  - numba==0.59.1
  - numpy==1.26.4
  - pandapower==2.14.6
  - pandas==2.2.2
  - scikit-learn==1.4.2
  - scipy==1.13.0
  - spyder==5.5.1
  - spyder-kernels==2.5.1
  - cvxopt==1.3.2
  - matplotlib==3.8.4
  - seaborn==0.13.2
  - openpyxl==3.1.2
  - gurobi==11.0.3
  - gurobi-logtools==3.1.0
  - pip:
      - PYPOWER==5.1.16
      - cvxpy==1.6.3
      - PICOS==2.4.17

